### ISSUE TITLE
Ship token simulation by default

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe-modeler#12]
The [token simulation plugin](https://github.com/philippfromme/bpmn-js-token-simulation-plugin) should be included by default. Zeebe targets people not yet familiar with BPMN and token simulation is great for understanding BPMN control flow constructs.

**Comment by dominikhrn** [comment]
@ThorbenLindhauer  The simulation plugin has no support for a SendTask. Should I add it anyway?

**Comment by ThorbenLindhauer** [comment]
@dominikhrn I'd say yes. The plugin is disabled by default, so that should be fine.

By the way, thanks for your efforts of maintaining this project!

**Comment by jwulf** [comment]
Hey, this plugin is cool! I just added it to the Zeebe modeler and it's great.

**Comment by nikku** [comment]
We'll most likely not do this but rather incorporate something like the [Camunda Playground](https://github.com/nikku/camunda-playground) (in a Zeebe Version). The idea is that it is more beneficial to run it on the real thing (Zeebe) rather than having two engines to run on.

Hope this makes sense.
