### ISSUE TITLE
diagram crash after copy&paste

### ISSUE THREAD

**Issue by mschoe** [zeebe-io/zeebe-modeler#134]
__Describe the Bug__

__Steps to Reproduce__

1. Open the attached diagram
2. select all diagram elements and copy them into a new diagram

__Problem__
the diagram crashes (see application log).

[order_vinyl.bpmn.txt](https://github.com/zeebe-io/zeebe-modeler/files/3751161/order_vinyl.bpmn.txt)

__Environment__

zeebe modeler 0.7.0
linux mint 19.2

**Comment by nikku** [comment]
What is the content of the application log? Hint: You can copy it via the `copy` button.

**Comment by oguzeroglu** [comment]
@mschoe Nice catch!

**Comment by oguzeroglu** [comment]
By having a first look the problem seems to be copy/pasting flows with labels. It's not about pasting to a separate tab.

![Kapture 2019-10-21 at 16 19 02](https://user-images.githubusercontent.com/15003836/67213631-9eaf5e00-f41e-11e9-876e-8230338c5278.gif)

**Comment by oguzeroglu** [comment]
So the problem seems to be that when we copy a flow with label, LabelBehavior tries to call moveShape for the label, however this happens during elements.create and since the flow is created before the label, app crashes (label has no parent yet because it is not created yet).

I implemented this solution and it works, @nikku @philippfromme what do you think about this solution?

Inside modeling.createElements, we check if elements array contain a label, this label has a labelTarget which is inside the elements array and if the index of the label within the elements array is greater than its labelTarget's index (that means the label will be created after it's labelTarget is created), we shuffle their positions inside the array:

This is the code (would be beautified later):

`  elements.filter(function(element) {
    return !!element.labelTarget
  }).forEach(function(element) {
    var labelIndex = elements.indexOf(element);
    var labelTargetIndex = elements.indexOf(element.labelTarget)
    if (labelTargetIndex !== -1 && labelIndex > labelTargetIndex) {
      var labelTarget = elements[labelTargetIndex];
      elements[labelIndex] = labelTarget;
      elements[labelTargetIndex] = element;
    }
  });`

**Comment by oguzeroglu** [comment]
Closed by #135
