### ISSUE TITLE
Is it possible to run this as a web app without much changes

### ISSUE THREAD

**Issue by ysaakpr** [zeebe-io/zeebe-modeler#144]
I would like to use the modeler applicatoin as  webapp as hosted in the demo.bpmn.io. Are there any possibilities to support that on this application.

**Comment by pinussilvestrus** [comment]
You can refer to [this closed issue](https://github.com/zeebe-io/zeebe-modeler/issues/127) as a reference.

Basically saying, it's possible to have this as a web app. You will just have to build it as a normal bpmn-js web application (like shown in the linked issue above) and include the [zeebe related moddle descriptors](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/app/tabs/bpmn/custom/zeebe-bpmn-moddle/zeebe.json) into it.

Please ask if you need help with this. I'll close this issue since no real feature request or bug is described.
