### ISSUE TITLE
mac version 0.8.0 cannot be opened (security)

### ISSUE THREAD

**Issue by jangalinski** [zeebe-io/zeebe-modeler#205]
It seems to be the same issue as https://github.com/camunda/camunda-modeler/issues/1572

With latest osx, the file can not be analyzed and the developer is not trusted. It requires additional security measures to manually allow to open the zeebe modeller.

With the camunda modeller, this was already fixed, maybe this is possible here too?

**Comment by nikku** [comment]
Could you please use the bug report template and provide all necessary information?

For example, what is the latest release you are referring to?

**Comment by nikku** [comment]
Could you also double check if the MacOS nightly (https://zeebe-modeler-nightly.s3.eu-central-1.amazonaws.com/zeebe-modeler-nightly-mac.dmg) works for you?

**Comment by barmac** [comment]
This will be fixed in the upcoming 0.9.0 release. For the current release, you can rightclick the `.app` file and then use the _open_ option from the context menu. After that, the warning dialog should display the _open_ button.

I am closing this issue as a duplicate of https://github.com/zeebe-io/zeebe-modeler/issues/148.

**Comment by barmac** [comment]
See also https://support.apple.com/en-gb/HT202491. No additional permissions apart from allowing apps outside of App Store are required. The latter will still be required for the upcoming release, as we are not using App Store at the moment.

**Comment by jangalinski** [comment]
cool, thanks @barmac
