### ISSUE TITLE
Remove unnecessary extra steps

### ISSUE THREAD

**Issue by ultraschuppi** [zeebe-io/zeebe-modeler#270]
__Is your feature request related to a problem? Please describe.__

The default path for creating a new zeebe model from scratch does not produce a deployable zeebe model. Extra steps are needed that I see as not necessary.

__Describe the solution you'd like__

* default task-type should be Service-Task. The standard task is not accepted on deployment anyway, so maybe just make service-task the default?
* even after selecting service-task as the task-type, I need to manually fill in 'type' in the properties panel under `details`. what about having a default there?

Ideal click path:
* open zeebe modeller
* add task after existing start event
* add end-event
* deploy

**Comment by pinussilvestrus** [comment]
Feels a bit like we're turning in circles since we actively removed this a while ago, cf. https://github.com/zeebe-io/zeebe-modeler/issues/113

Seems like there was also some discussion around this after we made those changes, cf. https://github.com/zeebe-io/zeebe-modeler/issues/204#issuecomment-612156555

Minimize the steps to create a deployable diagram makes a lot of sense to me, especially if we find out the current default won't be deployable any time soon.

**Comment by MaxTru** [comment]
Will take this to PM alignment with Volker next Tuesday

**Comment by ultraschuppi** [comment]
sorry, haven't caught up on the history of all of this yet ;-)

my expectation as a user: 
* I should only see stuff in the zeebe modeler that is actually supported by zeebe
* for first time users there should be as easy as possible to come up with a deployable model, w/o the need to read through docs or howtos too much

**Comment by nikku** [comment]
We've discussed this internally and decided that we'll not go back to service task first modeling. The reason is many-fold but in summary https://github.com/zeebe-io/zeebe-modeler/issues/204#issuecomment-612156555 still applies.

What we'll do in the future is carefully examine the getting started (and getting to production) journey. There is many things we can do in that realm, including guiding users in "what does it mean to make a task executable" in a tutorial style fashion. Alternatives include ready made templates that they just need to press "deploy" on, no modeling at all involved.

This comment applies to the Zeebe Modeler as an app. Down the toolkit level it is fairly trivial [to implement a service-task only mode](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements#customize-editor-controls) as a bpmn-js extension or even a Zeebe Modeler plug-in.

**Comment by ultraschuppi** [comment]
thanks for elaborating @nikku
